import random

responses = [
    "Pay off high-interest debt first to save money in the long run.",
    "Consider a debt snowball or avalanche method for repayment.",
    "Avoid taking on debt for non-essential purchases.",
    "Create a debt repayment plan and stick to it.",
    "Understand the importance of budgeting when managing debt.",
    "Track your progress as you pay off debts to stay motivated.",
    "Consider consolidating debt for lower interest rates.",
    "Use extra income to make additional debt payments.",
    "Communicate with creditors if you're having trouble making payments.",
    "Avoid taking on more debt while trying to pay off existing debt.",
    "Set realistic timelines for debt repayment.",
    "Explore debt counseling options if you're overwhelmed.",
    "Avoid using credit cards for everyday purchases if you're in debt.",
    "Consider negotiating with creditors for better repayment terms.",
    "Understand the impact of debt on your credit score.",
    "Learn about the difference between secured and unsecured debt.",
    "Stay committed to your debt repayment plan for success.",
    "Celebrate milestones in your debt repayment journey.",
    "Educate yourself on the psychology of debt and spending.",
    "Consider the impact of interest rates when taking on debt.",
    "Keep a budget that prioritizes debt repayment.",
    "Avoid payday loans; they often lead to more debt.",
    "Consider utilizing a debt repayment calculator.",
    "Seek support from friends or family in your debt repayment journey.",
    "Avoid emotional spending to help manage debt.",
    "Understand that it’s okay to ask for help with debt management.",
    "Keep your goals in sight to stay motivated during debt repayment.",
    "Prioritize your debts based on interest rates and terms.",
    "Stay informed about your rights as a debtor.",
    "Consider using a financial advisor to help with debt strategies.",
    "Educate yourself on the impact of debt on your overall financial health.",
    "Use budgeting tools to help manage your debt payments.",
    "Learn to identify the triggers that lead to debt accumulation.",
    "Stay proactive in managing debt to prevent future issues.",
    "Consider setting up automatic payments for debt to avoid late fees.",
    "Understand the benefits of being debt-free for financial freedom.",
    "Avoid comparing your financial situation to others; focus on your journey.",
    "Consider a balance transfer credit card for high-interest debt.",
    "Develop a plan to avoid accumulating new debt.",
    "Stay patient; debt repayment takes time and dedication.",
    "Create a support network for accountability in debt management.",
    "Consider using the debt avalanche method to minimize interest paid.",
    "Evaluate your spending habits regularly to prevent new debt.",
    "Stay focused on your financial goals, even when it's challenging.",
    "Learn about the long-term effects of debt on financial stability.",
    "Consider leveraging community resources for debt management support.",
    "Avoid quick fixes; focus on sustainable debt repayment strategies.",
]

def get_debt_response():
    return random.choice(responses)
